### ISSUE TITLE
Caffeine version bump request

### ISSUE THREAD

**Issue by jorgicio** [vonavi/seeds#3]
Hi!
A few days ago, Caffeine released the 2.9 branch, now the current version is 2.9.3. I don't know exactly if there's a fix for mate-screensaver but it seems not.
Anyways, there's the notice.
Thanks.

**Comment by vonavi** [comment]
Hello, Jorge!
Thank you for the remainder; the ebuild has been updated. Script `caffeine-screensaver` is not shipped by the new version.
Best regards, Vladimir.

**Comment by jorgicio** [comment]
Thanks for the ebuild. Just some things to mention:
1. python3-xlib is not needed anymore as a dependency because recent versions of dev-python/python-xlib already support Python 3.
2. Patches used in 2.8.\* are not needed anymore because the package is entirely using the xdg API and also is pure Python.
3. use EAPI=6 instead of the 5 version, and also the linguas_\* USE-flags are being replaced with l10n_*.
4. EWMH also supports Python 2.

Thanks.

**Comment by vonavi** [comment]
Thanks again. I changed the ebuild in accordance with your suggestions.
P.S. Caffeine does not work with python-2.7.
Best regards,
Vladimir.

**Comment by jorgicio** [comment]
Thanks again. Tried the package recently and it's not working, then I checked your ebuild and you added the Python 2.7 support to the Caffeine ebuild, but Caffeine supports Python 3 only (the Python 2.7 support as I mentioned above is only for ewmh). Also, in that ebuild (and in the ewmh one) you forgot to add support to Python 3.5.
Thanks again!
Best regards.

**Comment by vonavi** [comment]
Sorry for that. I just made a forced update of the ebuilds (two last commits).
Best regard,
Vladimir.

**Comment by jorgicio** [comment]
Perfect, that's now fixed.
Thank you!
Best regards.
