### ISSUE TITLE
Add support to Python 3.6 for x11-misc/caffeine

### ISSUE THREAD

**Issue by jorgicio** [vonavi/seeds#4]
Hi!

Python 3.6 in Gentoo Portage became stable. However, the caffeine package has disabled the Python 3.6 support. Please, consider to add it.
Thanks.

**Comment by vonavi** [comment]
Hello @jorgicio ! Thank you for the remainder. I added a newer version of Caffeine with the Python 3.6 support. Please contact me if you will still have this problem.

**Comment by jorgicio** [comment]
Thanks for the response ;) Also, I noted another of your packages, ewmh, needs Python 3.6 support too.

Thanks again!

**Comment by vonavi** [comment]
OK. Now it should work too.

**Comment by jorgicio** [comment]
Thanks. Now it's done ;)
