### ISSUE TITLE
kde-misc/kde-plasma-alarm-clock-1.7 quite outdated and throws error at cache

### ISSUE THREAD

**Issue by jorgicio** [vonavi/seeds#5]
Hi!

This happens everytime I sync your repo:
``hackenherr:~ # emaint sync -r seeds                                                                                                                            [20:24:56]
>>> Syncing repository 'seeds' into '/var/db/repos/seeds'...
/usr/bin/git pull
Already up to date.
=== Sync completed for seeds
q: Updating ebuild cache in /var/db/repos/seeds ... 
q: Finished 34 entries in 0.000433 seconds
 * Updating metadata cache for seeds ...
 * ERROR: kde-misc/kde-plasma-alarm-clock-1.7::seeds failed (depend phase):
 *   kde4-base.eclass could not be found by inherit()
 * 
 * Call stack:
 *                           ebuild.sh, line 635:  Called source '/var/db/repos/seeds/kde-misc/kde-plasma-alarm-clock/kde-plasma-alarm-clock-1.7.ebuild'
 *   kde-plasma-alarm-clock-1.7.ebuild, line   9:  Called inherit 'python-single-r1' 'kde4-base'
 *                           ebuild.sh, line 300:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=kde-misc/kde-plasma-alarm-clock-1.7::seeds'`,
 * the complete build log and the output of `emerge -pqv '=kde-misc/kde-plasma-alarm-clock-1.7::seeds'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/var/tmp/portage/kde-misc/kde-plasma-alarm-clock-1.7/work/kde-plasma-alarm-clock-1.7'
Error processing kde-misc/kde-plasma-alarm-clock-1.7, continuing...                                                                                                 [ !! ]
 * Spawn failed for: sync_overlay_cache, /etc/portage/repo.postsync.d/sync_overlay_cache
``
I noted that package is quite outdated as well as the eclass mentioned above.
Thanks.

**Comment by vonavi** [comment]
Hi @jorgicio ! Thank you for the notice. I removed the ebuild.
